### ISSUE TITLE
Back end: UNCAUGHT ERROR undefined

### ISSUE THREAD

**Issue by HuanYu-Tan** [SELab-2/OSOC-2#545]
**Describe the bug**
Backend throws a UNCAUGHT ERROR undefined

**To Reproduce**
1. Go to Settings
2. Click on Fill your current password to "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" and the new password to the same
3. Go to the backend terminal

**Expected behavior**
The server doesn't throw an error

**Screenshots**
![image](https://user-images.githubusercontent.com/99679456/166783816-53611bf2-ca2a-4588-8a0a-c4296649a18e.png)

**Comment by jay-tux** [comment]
**Bug encountered on branch** frontend-testing

Since that branch doesn't change any BE files, might also occur on dev.

**Comment by jay-tux** [comment]
Seems like a bug caused by [backend/routes/user.ts:307](https://github.com/SELab-2/OSOC-2/blob/2f358c50210c5dbb8765ee2f678df323879fdb84/backend/routes/user.ts#L307). We forgot to add the `.catch` or we forgot to return an appropriate error value.

I'm guessing you entered an invalid password in the current password field (which makes the check around that line fail, and thus causes the error).
